# Generated by Django 4.1.5 on 2023-02-19 21:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nuevaReserva', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='nuevaReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('fechaReserva', models.DateField()),
                ('hora', models.TimeField()),
                ('cantidadPersonas', models.PositiveIntegerField()),
                ('telefono', models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='Formato incorrecto', regex='^\\+?1?\\d{9,15}$')])),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nuevaReserva.estadoreserva')),
            ],
        ),
    ]
