# Generated by Django 4.1.5 on 2023-02-20 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nuevaReserva', '0003_estadomesa'),
    ]

    operations = [
        migrations.CreateModel(
            name='mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nuevaReserva.estadomesa')),
            ],
        ),
    ]
