# Generated by Django 4.1.5 on 2023-02-20 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuevaReserva', '0005_alter_nuevareserva_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nuevareserva',
            name='hora',
            field=models.TimeField(),
        ),
    ]
