# Generated by Django 4.1.5 on 2023-02-22 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuevaReserva', '0008_alter_nuevareserva_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nuevareserva',
            name='apellido',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
