# Generated by Django 4.1.5 on 2023-02-22 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nuevaReserva', '0009_alter_nuevareserva_apellido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nuevareserva',
            name='apellido',
        ),
    ]
