# Generated by Django 4.1.5 on 2023-02-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuevaReserva', '0010_remove_nuevareserva_apellido'),
    ]

    operations = [
        migrations.AddField(
            model_name='nuevareserva',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
