# Generated by Django 4.1.5 on 2023-03-17 13:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nuevaReserva', '0011_nuevareserva_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='nuevareserva',
            name='mesa_asignadaa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='nuevareserva',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
         migrations.AlterField(
            model_name='nuevareserva',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='mesaNoo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nuevaReserva.estadomesa')),
            ],
        ),
    ]
