# Generated by Django 4.1.5 on 2023-03-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuevaReserva', '0012_nuevareserva_mesa_asignadaa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='incidenciaDelDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaIncidedncia', models.DateField()),
                ('detalleIncidencia', models.TextField(blank=True)),
                ('usuario', models.CharField(max_length=50)),
            ],
        ),
    ]
