# Generated by Django 4.1.5 on 2023-03-19 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuevaReserva', '0013_incidenciadeldia'),
    ]

    operations = [
        migrations.AddField(
            model_name='nuevareserva',
            name='mails',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='nuevareserva',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
