# Generated by Django 4.1.5 on 2023-03-21 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuevaReserva', '0013_nuevareserva_emailr'),
    ]

    operations = [
        migrations.CreateModel(
            name='incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_incidencia', models.DateField()),
                ('mesa_incidencia', models.CharField(blank=True, max_length=10, null=True)),
                ('mozo_incidencia', models.CharField(blank=True, max_length=50, null=True)),
                ('detalle_incidencia', models.TextField()),
                ('fecha_registro', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
