# Generated by Django 4.1.5 on 2023-03-24 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuevaReserva', '0014_incidencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='anfitriona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_anfitriona', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='mozosPlaza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mozo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='plazaAlmuerzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_dia', models.DateField(auto_now_add=True)),
                ('mozo_nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('m1', models.CharField(blank=True, max_length=20, null=True)),
                ('r1', models.CharField(blank=True, max_length=20, null=True)),
                ('m2', models.CharField(blank=True, max_length=20, null=True)),
                ('r2', models.CharField(blank=True, max_length=20, null=True)),
                ('m3', models.CharField(blank=True, max_length=20, null=True)),
                ('r3', models.CharField(blank=True, max_length=20, null=True)),
                ('m4', models.CharField(blank=True, max_length=20, null=True)),
                ('r4', models.CharField(blank=True, max_length=20, null=True)),
                ('m5', models.CharField(blank=True, max_length=20, null=True)),
                ('r5', models.CharField(blank=True, max_length=20, null=True)),
                ('total', models.CharField(blank=True, max_length=20, null=True)),
                ('plaza', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_anfitriona', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='plazaCena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_dia', models.DateField(auto_now_add=True)),
                ('mozo_nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('m1', models.CharField(blank=True, max_length=20, null=True)),
                ('r1', models.CharField(blank=True, max_length=20, null=True)),
                ('m2', models.CharField(blank=True, max_length=20, null=True)),
                ('r2', models.CharField(blank=True, max_length=20, null=True)),
                ('m3', models.CharField(blank=True, max_length=20, null=True)),
                ('r3', models.CharField(blank=True, max_length=20, null=True)),
                ('m4', models.CharField(blank=True, max_length=20, null=True)),
                ('r4', models.CharField(blank=True, max_length=20, null=True)),
                ('m5', models.CharField(blank=True, max_length=20, null=True)),
                ('r5', models.CharField(blank=True, max_length=20, null=True)),
                ('total', models.CharField(blank=True, max_length=20, null=True)),
                ('plaza', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_anfitriona', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
