# Generated by Django 4.1.5 on 2023-03-30 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuevaReserva', '0015_anfitriona_mozosplaza_plazaalmuerzo_plazacena'),
    ]

    operations = [
        migrations.CreateModel(
            name='plazaAlmuerzoMan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_dia', models.DateField(auto_now_add=True)),
                ('n1', models.CharField(blank=True, max_length=20, null=True)),
                ('n3', models.CharField(blank=True, max_length=20, null=True)),
                ('n4', models.CharField(blank=True, max_length=20, null=True)),
                ('n5', models.CharField(blank=True, max_length=20, null=True)),
                ('plaza', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='plazaCenaMan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_dia', models.DateField(auto_now_add=True)),
                ('n1', models.CharField(blank=True, max_length=20, null=True)),
                ('n2', models.CharField(blank=True, max_length=20, null=True)),
                ('n3', models.CharField(blank=True, max_length=20, null=True)),
                ('n4', models.CharField(blank=True, max_length=20, null=True)),
                ('n5', models.CharField(blank=True, max_length=20, null=True)),
                ('plaza', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
