# Generated by Django 4.1.5 on 2023-03-30 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuevaReserva', '0016_plazaalmuerzoman_plazacenaman'),
    ]

    operations = [
        migrations.AddField(
            model_name='plazaalmuerzoman',
            name='n2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
