# Generated by Django 4.1.5 on 2023-07-07 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuevaReserva', '0017_plazaalmuerzoman_n2'),
    ]

    operations = [
        migrations.AddField(
            model_name='nuevareserva',
            name='origen_reserva',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
