# Generated by Django 4.1.5 on 2023-07-17 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuevaReserva', '0018_nuevareserva_origen_reserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='incidenciaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_incidencia', models.DateField()),
                ('detalle_incidencia', models.TextField()),
                ('fecha_registro', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
